/* ../err/ccs_err.c */
/* ====================================================================
 * Copyright (c) 1999-2018 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.OpenSSL.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@OpenSSL.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.OpenSSL.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

/*
 * NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include "ccs_err.h"

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_CCS,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_CCS,0,reason)

static ERR_STRING_DATA CCS_str_functs[] = {
    {ERR_FUNC(CCS_F_ASN1_REGISTRATION), "ASN1_REGISTRATION"},
    {ERR_FUNC(CCS_F_ASN1_SELECT), "ASN1_SELECT"},
    {ERR_FUNC(CCS_F_ECDH_DERIVE), "ECDH_DERIVE"},
    {ERR_FUNC(CCS_F_ECDSA_DO_SIGN), "ECDSA_DO_SIGN"},
    {ERR_FUNC(CCS_F_ECDSA_DO_VERIFY), "ECDSA_DO_VERIFY"},
    {ERR_FUNC(CCS_F_ECIES_DECRYPT), "ECIES_DECRYPT"},
    {ERR_FUNC(CCS_F_ECIES_ENCRYPT), "ECIES_ENCRYPT"},
    {ERR_FUNC(CCS_F_EC_COMPUTE_PUBLIC), "EC_COMPUTE_PUBLIC"},
    {ERR_FUNC(CCS_F_EC_FILLING_PARAMETER), "EC_FILLING_PARAMETER"},
    {ERR_FUNC(CCS_F_EC_KEY_GEN), "EC_KEY_GEN"},
    {ERR_FUNC(CCS_F_EC_PARAMETER_GEN), "EC_PARAMETER_GEN"},
    {ERR_FUNC(CCS_F_MD_SELECT), "MD_SELECT"},
    {ERR_FUNC(CCS_F_PKEY_CTX_INIT), "PKEY_CTX_INIT"},
    {ERR_FUNC(CCS_F_PKEY_REGISTRATION), "PKEY_REGISTRATION"},
    {ERR_FUNC(CCS_F_PKEY_SELECT), "PKEY_SELECT"},
    {ERR_FUNC(CCS_F_RESERVED), "RESERVED"},
    {0, NULL}
};

static ERR_STRING_DATA CCS_str_reasons[] = {
    {ERR_REASON(CCS_R_ARITHMETIC_ERROR), "arithmetic error"},
    {ERR_REASON(CCS_R_BN_ERROR), "bn error"},
    {ERR_REASON(CCS_R_EC_PARAMETER_ERROR), "ec parameter error"},
    {ERR_REASON(CCS_R_MALLOC_ERROR), "malloc error"},
    {ERR_REASON(CCS_R_NULL_REFERENCE), "null reference"},
    {ERR_REASON(CCS_R_PARAMETER_ERROR), "parameter error"},
    {ERR_REASON(CCS_R_PKEY_SET_ERROR), "pkey set error"},
    {ERR_REASON(CCS_R_RESERVED), "reserved"},
    {ERR_REASON(CCS_R_UNDEF_CURVE_ID), "undef curve id"},
    {ERR_REASON(CCS_R_UNSUPPORTED_ALGORITHM), "unsupported algorithm"},
    {0, NULL}
};

#endif

void ERR_load_CCS_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(CCS_str_functs[0].error) == NULL) {
        ERR_load_strings(0, CCS_str_functs);
        ERR_load_strings(0, CCS_str_reasons);
    }
#endif
}
