/* ====================================================================
 * Copyright (c) 2001-2018 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@openssl.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

#ifndef HEADER_CCS_ERR_H
# define HEADER_CCS_ERR_H

# ifdef  __cplusplus
extern "C" {
# endif

/*
 * FIXME LIB ID
 * ERR_LIB_CCS is not auto generated, and may conflict with further version.
 */
#define ERR_LIB_CCS            255

#define CCSerr(f, r) ERR_PUT_error(ERR_LIB_CCS, (f), (r), __FILE__, __LINE__)

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */

void ERR_load_CCS_strings(void);

/* Error codes for the CCS functions. */

/* Function codes. */
# define CCS_F_ASN1_REGISTRATION                          102
# define CCS_F_ASN1_SELECT                                114
# define CCS_F_CIPHER_CTRL                                116
# define CCS_F_CIPHER_INIT                                117
# define CCS_F_CIPHER_SELECT                              119
# define CCS_F_DO_CIPHER                                  118
# define CCS_F_ECDH_DERIVE                                103
# define CCS_F_ECDSA_DO_SIGN                              104
# define CCS_F_ECDSA_DO_VERIFY                            105
# define CCS_F_ECIES_DECRYPT                              106
# define CCS_F_ECIES_ENCRYPT                              107
# define CCS_F_EC_COMPUTE_PUBLIC                          108
# define CCS_F_EC_FILLING_PARAMETER                       109
# define CCS_F_EC_KEY_GEN                                 110
# define CCS_F_EC_PARAMETER_GEN                           111
# define CCS_F_MD_SELECT                                  101
# define CCS_F_PKEY_CTX_INIT                              112
# define CCS_F_PKEY_REGISTRATION                          113
# define CCS_F_PKEY_SELECT                                115
# define CCS_F_RESERVED                                   100

/* Reason codes. */
# define CCS_R_ARITHMETIC_ERROR                           103
# define CCS_R_BN_ERROR                                   104
# define CCS_R_EC_PARAMETER_ERROR                         105
# define CCS_R_INVALID_OPERATION                          110
# define CCS_R_MALLOC_ERROR                               102
# define CCS_R_NULL_REFERENCE                             106
# define CCS_R_PARAMETER_ERROR                            107
# define CCS_R_PKEY_SET_ERROR                             108
# define CCS_R_RESERVED                                   100
# define CCS_R_UNDEF_CURVE_ID                             109
# define CCS_R_UNSUPPORTED_ALGORITHM                      101

# ifdef  __cplusplus
}
# endif
#endif
